version: "3.7"

services:
  app:
    build: .
    container_name: vitals_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python app.py

  mongo:
    image: mongo:6.0
    container_name: vitals_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: